Использовал
git
dataset по раковым клеткам груди
все через pip install
gridsearch


Скачать можно все, установив git и выполнивы команду 
```
git clone https://github.com/sbatururimi/teaching_wed5_light.git
```

Затем:
1) создать окружение с conda/virtualenv c python3.6 или выше
2) активировать окружение
3) выполнить
```
pip install -r pip_requirements.txt
```
(файл в комплекте)



https://git-scm.com/downloads
https://keras.io/search.html?q=fit
https://www.tensorflow.org/guide/keras

# Modules

In [37]:
import os
import pandas as pd

import wrangle as wr

from numpy import nan

from keras.utils import to_categorical
from keras.wrappers.scikit_learn import KerasClassifier

/bin/sh: run: command not found


# Exploratory data analysis

In [10]:
%ls

1_knobs.png               4_babysitting.png         7_early stopping.png
2_dnn.png                 5_gridsearch.png          breast_cancer.csv
3_iterative process.png   6_random search.png       hyperparams tuning.ipynb


In [35]:
df = pd.read_csv("breast_cancer.csv")
df.head(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   
7  ...          28.14           110.60       897.0            0.1654   
8  ...          30.73           106.20       739.3            0.1703   
9  ...          40.68            97.65       711.4            0.1853   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   
7             0.3682           0.2678                0.1556          0.3196   
8             0.5401           0.5390                0.2060          0.4378   
9             1.0580           1.1050                0.2210          0.4366   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  
7                  0.11510          NaN  
8                  0.10720          NaN  
9                  0.20750          NaN  

[10 rows x 33 columns]

In [36]:
len(df.columns)

33

In [16]:
df.drop("Unnamed: 32", axis=1, inplace=True)
df.drop("id", axis=1, inplace=True)

In [17]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [18]:
df["diagnosis"].head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object

In [19]:
y = df.diagnosis.values
x = df.drop("diagnosis", axis=1).values

In [21]:
print(y)

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B

In [24]:
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [30]:
# normalize every features to mean 0, std 1 
df = pd.DataFrame(x)  
x = (df - df.mean()) / df.std()
x.head()

0         1         2         3         4         5         6   \
0  1.096100 -2.071512  1.268817  0.983510  1.567087  3.280628  2.650542   
1  1.828212 -0.353322  1.684473  1.907030 -0.826235 -0.486643 -0.023825   
2  1.578499  0.455786  1.565126  1.557513  0.941382  1.052000  1.362280   
3 -0.768233  0.253509 -0.592166 -0.763792  3.280667  3.399917  1.914213   
4  1.748758 -1.150804  1.775011  1.824624  0.280125  0.538866  1.369806   

         7         8         9   ...        20        21        22        23  \
0  2.530249  2.215566  2.253764  ...  1.885031 -1.358098  2.301575  1.999478   
1  0.547662  0.001391 -0.867889  ...  1.804340 -0.368879  1.533776  1.888827   
2  2.035440  0.938859 -0.397658  ...  1.510541 -0.023953  1.346291  1.455004   
3  1.450431  2.864862  4.906602  ... -0.281217  0.133866 -0.249720 -0.549538   
4  1.427237 -0.009552 -0.561956  ...  1.297434 -1.465481  1.337363  1.219651   

         24        25        26        27        28        29  
0  1.306537  2.614365  2.107672  2.294058  2.748204  1.935312  
1 -0.375282 -0.430066 -0.146620  1.086129 -0.243675  0.280943  
2  0.526944  1.081980  0.854222  1.953282  1.151242  0.201214  
3  3.391291  3.889975  1.987839  2.173873  6.040726  4.930672  
4  0.220362 -0.313119  0.612640  0.728618 -0.867590 -0.396751  

[5 rows x 30 columns]

In [31]:
x = x.values

In [32]:
x

array([[ 1.09609953, -2.0715123 ,  1.26881726, ...,  2.2940576 ,
         2.74820411,  1.93531174],
       [ 1.82821197, -0.35332152,  1.68447255, ...,  1.08612862,
        -0.24367526,  0.28094279],
       [ 1.5784992 ,  0.45578591,  1.56512598, ...,  1.95328166,
         1.15124203,  0.20121416],
       ...,
       [ 0.70166686,  2.04377549,  0.67208442, ...,  0.41370467,
        -1.10357792, -0.31812924],
       [ 1.83672491,  2.33440316,  1.98078127, ...,  2.28797231,
         1.9173959 ,  2.21768395],
       [-1.80681144,  1.22071793, -1.81279344, ..., -1.7435287 ,
        -0.04809589, -0.75054629]])

In [33]:
input_dim = x.shape[1]

In [34]:
input_dim

30

# Model

In [57]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten

def create_model(first_neuron=9, activation="relu", 
                 kernel_initializer="uniform", dropout_rate=0, optimizer="Adam"):
    """Neural network creation
    
    Args:
     first_neuron:....
     
    Returns:
    
    Assertions:
    """
    model = Sequential()
    model.add(Dense(first_neuron,
                   input_dim=input_dim,
                   kernel_initializer=kernel_initializer))
    
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, kernel_initializer=kernel_initializer, activation="sigmoid"))
    
    model.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])
    
    return model

In [58]:
model = KerasClassifier(build_fn=create_model)

In [59]:
help(create_model)

Help on function create_model in module __main__:

create_model(first_neuron=9, activation='relu', kernel_initializer='uniform', dropout_rate=0, optimizer='Adam')
    Neural network creation
    
    Args:
     first_neuron:....
     
    Returns:
    
    Assertions:



In [60]:
first_neurons = [8,9]
activation = ["relu", "elu"]
kernel_initializer = ["uniform", "normal"]
optimizer = ["Adam", "Nadam"]

epochs=[10]
batch_size = [1024]
dropout_rate = [0.0]

In [61]:
param_grid = dict(epochs = epochs,
                 batch_size=batch_size,
                optimizer=optimizer,
                 dropout_rate=dropout_rate,
                 kernel_initializer=kernel_initializer,
                 first_neuron=first_neurons)

In [62]:
param_grid

{'epochs': [10],
 'batch_size': [1024],
 'optimizer': ['Adam', 'Nadam'],
 'dropout_rate': [0.0],
 'kernel_initializer': ['uniform', 'normal'],
 'first_neuron': [8, 9]}

In [63]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=2, verbose=2)
grid_result = grid.fit(x, y)

Fitting 2 folds for each of 8 candidates, totalling 16 fits
[CV] batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=8, kernel_initializer=uniform, optimizer=Adam 
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Epoch 1/10
284/284 [==============================] - 1s 2ms/step - loss: 0.6928 - acc: 0.4965
Epoch 2/10
284/284 [==============================] - 0s 22us/step - loss: 0.6907 - acc: 0.6338
Epoch 3/10
284/284 [==============================] - 0s 17us/step - loss: 0.6887 - acc: 0.7817
Epoch 4/10
284/284 [==============================] - 0s 52us/step - loss: 0.6866 - acc: 0.8838
Epoch 5/10
284/284 [==============================] - 0s 23us/step - loss: 0.6846 - acc: 0.9225
Epoch 6/10
284/284 [==============================] - 0s 13us/step - loss: 0.6825 - acc: 0.9437
Epoch 7/10
284/284 [==============================] - 0s 22us/step - loss: 0.6803 - acc: 0.9577
Epoch 8/10
284/284 [==============================] - 0s 37us/step - loss: 0.6781 - acc: 0.9542
Epoch 9/10
284/284 [==============================] - 0s 23us/step - loss: 0.6758 - acc: 0.9542
Epoch 10/10
285/285 [==============================] - 0s 370us/step
[CV]  batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=8, 

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.4s remaining:    0.0s


Epoch 1/10
285/285 [==============================] - 1s 3ms/step - loss: 0.6928 - acc: 0.5579
Epoch 2/10
285/285 [==============================] - 0s 7us/step - loss: 0.6913 - acc: 0.7123
Epoch 3/10
285/285 [==============================] - 0s 10us/step - loss: 0.6898 - acc: 0.7544
Epoch 4/10
285/285 [==============================] - 0s 8us/step - loss: 0.6882 - acc: 0.8211
Epoch 5/10
285/285 [==============================] - 0s 54us/step - loss: 0.6866 - acc: 0.8596
Epoch 6/10
285/285 [==============================] - 0s 30us/step - loss: 0.6849 - acc: 0.8632
Epoch 7/10
285/285 [==============================] - 0s 10us/step - loss: 0.6832 - acc: 0.8737
Epoch 8/10
285/285 [==============================] - 0s 9us/step - loss: 0.6814 - acc: 0.8807
Epoch 9/10
285/285 [==============================] - 0s 17us/step - loss: 0.6796 - acc: 0.8842
Epoch 10/10
284/284 [==============================] - 0s 372us/step
[CV]  batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=8, ker

Epoch 9/10
285/285 [==============================] - 0s 15us/step - loss: 0.6483 - acc: 0.8982
Epoch 10/10
284/284 [==============================] - 0s 795us/step
[CV]  batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=8, kernel_initializer=normal, optimizer=Nadam, total=   2.3s
[CV] batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=9, kernel_initializer=uniform, optimizer=Adam 
Epoch 1/10
284/284 [==============================] - 1s 2ms/step - loss: 0.6990 - acc: 0.0810
Epoch 2/10
284/284 [==============================] - 0s 6us/step - loss: 0.6975 - acc: 0.1725
Epoch 3/10
284/284 [==============================] - 0s 7us/step - loss: 0.6955 - acc: 0.3275
Epoch 4/10
284/284 [==============================] - 0s 6us/step - loss: 0.6935 - acc: 0.5246
Epoch 5/10
284/284 [==============================] - 0s 9us/step - loss: 0.6914 - acc: 0.6514
Epoch 6/10
284/284 [==============================] - 0s 14us/step - loss: 0.6894 - acc: 0.7676
Epoch 7/10
284/284 [=======

Epoch 4/10
284/284 [==============================] - 0s 9us/step - loss: 0.6636 - acc: 0.8415
Epoch 5/10
284/284 [==============================] - 0s 6us/step - loss: 0.6579 - acc: 0.8627
Epoch 6/10
284/284 [==============================] - 0s 7us/step - loss: 0.6518 - acc: 0.8768
Epoch 7/10
284/284 [==============================] - 0s 9us/step - loss: 0.6452 - acc: 0.8908
Epoch 8/10
284/284 [==============================] - 0s 6us/step - loss: 0.6381 - acc: 0.9014
Epoch 9/10
284/284 [==============================] - 0s 6us/step - loss: 0.6305 - acc: 0.9049
Epoch 10/10
285/285 [==============================] - 0s 1ms/step
[CV]  batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=9, kernel_initializer=normal, optimizer=Nadam, total=   1.7s
[CV] batch_size=1024, dropout_rate=0.0, epochs=10, first_neuron=9, kernel_initializer=normal, optimizer=Nadam 
Epoch 1/10
285/285 [==============================] - 1s 4ms/step - loss: 0.6913 - acc: 0.5404
Epoch 2/10
285/285 [===========

[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:   28.8s finished


Epoch 1/10
569/569 [==============================] - 1s 2ms/step - loss: 0.7011 - acc: 0.2794
Epoch 2/10
569/569 [==============================] - 0s 7us/step - loss: 0.6983 - acc: 0.3673
Epoch 3/10
569/569 [==============================] - 0s 6us/step - loss: 0.6955 - acc: 0.4587
Epoch 4/10
569/569 [==============================] - 0s 10us/step - loss: 0.6927 - acc: 0.5536
Epoch 5/10
569/569 [==============================] - 0s 7us/step - loss: 0.6900 - acc: 0.6274
Epoch 6/10
569/569 [==============================] - 0s 8us/step - loss: 0.6874 - acc: 0.6837
Epoch 7/10
569/569 [==============================] - 0s 14us/step - loss: 0.6847 - acc: 0.7258
Epoch 8/10
569/569 [==============================] - 0s 5us/step - loss: 0.6821 - acc: 0.7645
Epoch 9/10
569/569 [==============================] - 0s 6us/step - loss: 0.6794 - acc: 0.8049
Epoch 10/10
569/569 [==============================] - 0s 12us/step - loss: 0.6767 - acc: 0.8225


In [64]:
print(grid_result.best_score_, grid_result.best_index_)

0.919156413610455 6


In [65]:
means = grid_result.cv_results_["mean_test_score"]
stds = grid_result.cv_results_["std_test_score"]
params = grid_result.cv_results_["params"]
for mean, std, param in zip(means, stds, params):
    print(f"{mean} ({std}) with: {param}")

0.8400703123877045 (0.026643145661219843) with: {'batch_size': 1024, 'dropout_rate': 0.0, 'epochs': 10, 'first_neuron': 8, 'kernel_initializer': 'uniform', 'optimizer': 'Adam'}
0.8875219421772211 (0.00019767849911226908) with: {'batch_size': 1024, 'dropout_rate': 0.0, 'epochs': 10, 'first_neuron': 8, 'kernel_initializer': 'uniform', 'optimizer': 'Nadam'}
0.7943760879429447 (0.058357953306975886) with: {'batch_size': 1024, 'dropout_rate': 0.0, 'epochs': 10, 'first_neuron': 8, 'kernel_initializer': 'normal', 'optimizer': 'Adam'}
0.8699472772844646 (0.0037435235384426875) with: {'batch_size': 1024, 'dropout_rate': 0.0, 'epochs': 10, 'first_neuron': 8, 'kernel_initializer': 'normal', 'optimizer': 'Nadam'}
0.8084358553056767 (0.004935763604323333) with: {'batch_size': 1024, 'dropout_rate': 0.0, 'epochs': 10, 'first_neuron': 9, 'kernel_initializer': 'uniform', 'optimizer': 'Adam'}
0.8980667890689494 (0.00685073867427026) with: {'batch_size': 1024, 'dropout_rate': 0.0, 'epochs': 10, 'first_ne